### ISSUE TITLE
Paper TO-DO Tracking

### ISSUE THREAD

**Issue by stanmatei** [stanmatei/NICE-S5#1]
Implementation work:
- [x] Implement Sigma-Delta before the MLP (right before or after the nonlinearity)
   - [ ] add logging of the activation sparsity (can be used from ReLU @stevenabreu7)
- [x] Implement ReLUfication: after Cx+Du, same place as the sigma-delta (before/after/instead GeLU) @stevenabreu7 
   - [ ] add logging of activation sparsity @stevenabreu7 
- [ ] ShiftAddLayer
   - [x] refactoring @stanmatei 
   - [x] Expand to matrix mul @stanmatei 
   - [x] Handle complex values @stanmatei 
   - [ ] verify the computations @kmheckel 

Experiments:
- [ ] Compare with baseline from Q-S5
- [ ] Compare Sigma Delta with ReLU
- [ ] Binary Activation Baseline

Setup:
- [x] WandB Project
